#!/usr/bin/env node
// ============================================================
// TurionZ — Interactive Setup Wizard
// Created by BollaNetwork
//
// Usage: npx ts-node src/setup.ts
//        or after build: node dist/setup.js
// ============================================================

import * as p from '@clack/prompts';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';
import * as http from 'http';

const VERSION = '0.1.0';
const ENV_PATH = path.join(process.cwd(), '.env');
const SOUL_DIR = path.join(process.cwd(), '.agents');

// ─── Helpers ───────────────────────────────────────────────

function httpGet(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

function httpPost(url: string, body: object, headers: Record<string, string>): Promise<{ status: number; body: string }> {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const parsed = new URL(url);
    const options = {
      hostname: parsed.hostname,
      path: parsed.pathname,
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) },
    };
    const client = url.startsWith('https') ? https : http;
    const req = client.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => (body += chunk));
      res.on('end', () => resolve({ status: res.statusCode || 0, body }));
    });
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

function runCmd(cmd: string, silent = true): string {
  try {
    return execSync(cmd, { encoding: 'utf-8', stdio: silent ? 'pipe' : 'inherit' }).trim();
  } catch {
    return '';
  }
}

function writeEnvFile(config: Record<string, string>): void {
  const lines = [
    '# ============================================================',
    '# TurionZ (Thor) — Environment Variables',
    '# Created by BollaNetwork — Auto-generated by setup wizard',
    '# ============================================================',
    '',
    '# --- Main Brain (Thor) ---',
    `MAIN_MODEL=${config.MAIN_MODEL}`,
    '',
    '# --- OpenRouter (All models) ---',
    `OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY}`,
    `SUB_AGENT_DEFAULT_MODEL=${config.SUB_AGENT_DEFAULT_MODEL}`,
    `ANALYSIS_MODEL=${config.ANALYSIS_MODEL}`,
    '',
    '# --- Telegram ---',
    `TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN}`,
    '',
    '# --- PostgreSQL ---',
    `DATABASE_URL=${config.DATABASE_URL}`,
    '',
    '# --- Agent Config ---',
    `MAX_ITERATIONS=${config.MAX_ITERATIONS}`,
    `CONTEXT_WINDOW_SIZE=${config.CONTEXT_WINDOW_SIZE}`,
    '',
    '# --- Owner ---',
    `OWNER_TELEGRAM_ID=${config.OWNER_TELEGRAM_ID}`,
    `OWNER_NAME=${config.OWNER_NAME}`,
    '',
    '# --- Optional ---',
    `DISCORD_BOT_TOKEN=${config.DISCORD_BOT_TOKEN || ''}`,
    `OWNER_DISCORD_ID=${config.OWNER_DISCORD_ID || ''}`,
    `OWNER_WHATSAPP_ID=${config.OWNER_WHATSAPP_ID || ''}`,
    `API_PORT=${config.API_PORT || '3000'}`,
    `API_ACCESS_KEY=${config.API_ACCESS_KEY || ''}`,
  ];
  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf-8');
}

// ─── Validators ────────────────────────────────────────────

async function validateOpenRouterKey(key: string): Promise<boolean> {
  try {
    const result = await httpPost(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        model: 'google/gemini-2.5-flash-preview',
        messages: [{ role: 'user', content: 'Say OK' }],
        max_tokens: 5,
      },
      {
        'Authorization': `Bearer ${key}`,
        'HTTP-Referer': 'https://bollanetwork.com',
        'X-Title': 'TurionZ Setup',
      }
    );
    return result.status === 200;
  } catch {
    return false;
  }
}

async function validateTelegramToken(token: string): Promise<{ valid: boolean; botName?: string }> {
  try {
    const data = await httpGet(`https://api.telegram.org/bot${token}/getMe`);
    const parsed = JSON.parse(data);
    if (parsed.ok) {
      return { valid: true, botName: parsed.result.first_name };
    }
    return { valid: false };
  } catch {
    return { valid: false };
  }
}

function validatePostgresUrl(url: string): boolean {
  return url.startsWith('postgresql://') || url.startsWith('postgres://');
}

// ─── Main Setup Flow ───────────────────────────────────────

async function main() {
  console.clear();

  p.intro(`
  ╔════════════════════════════════════════════════╗
  ║   ⚡ TurionZ (Thor) — Setup Wizard v${VERSION}      ║
  ║   Created by BollaNetwork                     ║
  ╚════════════════════════════════════════════════╝
  `);

  // Check existing .env
  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await p.confirm({
      message: 'Encontrei um .env existente. Deseja reconfigurar?',
      initialValue: false,
    });

    if (p.isCancel(overwrite) || !overwrite) {
      p.outro('Setup cancelado. Configuração existente mantida.');
      process.exit(0);
    }
  }

  // ─── Step 1: Setup Mode ──────────────────────────────────

  const mode = await p.select({
    message: 'Modo de instalação:',
    options: [
      { value: 'quick', label: 'QuickStart', hint: 'Configurações padrão, só preciso das chaves' },
      { value: 'manual', label: 'Manual', hint: 'Configuro tudo manualmente' },
    ],
  });

  if (p.isCancel(mode)) {
    p.cancel('Setup cancelado.');
    process.exit(0);
  }

  const config: Record<string, string> = {
    MAIN_MODEL: 'google/gemini-2.5-flash-preview',
    SUB_AGENT_DEFAULT_MODEL: 'google/gemini-2.5-flash-preview',
    ANALYSIS_MODEL: 'google/gemini-2.5-flash-preview',
    MAX_ITERATIONS: '5',
    CONTEXT_WINDOW_SIZE: '150000',
    API_PORT: '3000',
    DISCORD_BOT_TOKEN: '',
    OWNER_DISCORD_ID: '',
    OWNER_WHATSAPP_ID: '',
    API_ACCESS_KEY: '',
    TELEGRAM_BOT_TOKEN: '',
    OPENROUTER_API_KEY: '',
    DATABASE_URL: '',
    OWNER_TELEGRAM_ID: '',
    OWNER_NAME: '',
  };

  // ─── Step 2: OpenRouter API Key ──────────────────────────

  const openrouterKey = await p.text({
    message: 'OpenRouter API Key:',
    placeholder: 'sk-or-v1-...',
    validate(value) {
      if (!value || !value.startsWith('sk-or-')) return 'Chave deve começar com sk-or-';
      return undefined;
    },
  });

  if (p.isCancel(openrouterKey)) {
    p.cancel('Setup cancelado.');
    process.exit(0);
  }

  config.OPENROUTER_API_KEY = openrouterKey as string;

  // Validate key
  const keySpinner = p.spinner();
  keySpinner.start('Validando chave do OpenRouter...');

  const keyValid = await validateOpenRouterKey(config.OPENROUTER_API_KEY);
  if (keyValid) {
    keySpinner.stop('OpenRouter: Chave válida ✓');
  } else {
    keySpinner.stop('OpenRouter: Chave inválida ✗');
    p.log.warning('A chave não funcionou com Gemini 2.5 Flash. Verifique no painel do OpenRouter.');
    const continueAnyway = await p.confirm({ message: 'Continuar mesmo assim?' });
    if (p.isCancel(continueAnyway) || !continueAnyway) {
      p.cancel('Setup cancelado.');
      process.exit(0);
    }
  }

  // ─── Step 3: Model Selection (Manual mode) ───────────────

  if (mode === 'manual') {
    const mainModel = await p.select({
      message: 'Modelo principal do Thor:',
      options: [
        { value: 'google/gemini-2.5-flash-preview', label: 'Gemini 2.5 Flash', hint: '$0.30/1M — Melhor custo-benefício (Recomendado)' },
        { value: 'google/gemini-2.5-pro-preview', label: 'Gemini 2.5 Pro', hint: '$1.25/1M — Qualidade premium' },
        { value: 'deepseek/deepseek-v3.2', label: 'DeepSeek V3.2', hint: '$0.26/1M — Ultra barato, boa qualidade' },
        { value: 'openai/gpt-4o', label: 'GPT-4o', hint: '$2.50/1M — Tool calling preciso' },
        { value: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4', hint: '$3.00/1M — Melhor personalidade' },
        { value: 'custom', label: 'Outro modelo', hint: 'Digitar ID do modelo manualmente' },
      ],
    });

    if (p.isCancel(mainModel)) {
      p.cancel('Setup cancelado.');
      process.exit(0);
    }

    if (mainModel === 'custom') {
      const customModel = await p.text({
        message: 'ID do modelo no OpenRouter (ex: meta-llama/llama-4-maverick):',
      });
      if (!p.isCancel(customModel)) {
        config.MAIN_MODEL = customModel as string;
      }
    } else {
      config.MAIN_MODEL = mainModel as string;
    }

    const subModel = await p.select({
      message: 'Modelo padrão dos sub-agents:',
      options: [
        { value: 'google/gemini-2.5-flash-preview', label: 'Gemini 2.5 Flash', hint: '$0.30/1M — Recomendado' },
        { value: 'openai/gpt-4o-mini', label: 'GPT-4o Mini', hint: '$0.15/1M — Barato e confiável' },
        { value: 'mistralai/mistral-small-3.1-24b-instruct', label: 'Mistral Small 3.1', hint: '$0.03/1M — Ultra barato' },
        { value: 'deepseek/deepseek-v3.2', label: 'DeepSeek V3.2', hint: '$0.26/1M — Bom custo-benefício' },
      ],
    });

    if (!p.isCancel(subModel)) {
      config.SUB_AGENT_DEFAULT_MODEL = subModel as string;
    }
  }

  // ─── Step 4: Telegram ────────────────────────────────────

  p.log.info('Crie um bot no Telegram: abra @BotFather, envie /newbot e siga os passos.');

  const telegramToken = await p.text({
    message: 'Telegram Bot Token:',
    placeholder: '123456:ABC-DEF...',
    validate(value) {
      if (!value || !value.includes(':')) return 'Token deve conter ":"';
      return undefined;
    },
  });

  if (p.isCancel(telegramToken)) {
    p.cancel('Setup cancelado.');
    process.exit(0);
  }

  config.TELEGRAM_BOT_TOKEN = telegramToken as string;

  // Validate token
  const tgSpinner = p.spinner();
  tgSpinner.start('Validando token do Telegram...');

  const tgResult = await validateTelegramToken(config.TELEGRAM_BOT_TOKEN);
  if (tgResult.valid) {
    tgSpinner.stop(`Telegram: Bot "${tgResult.botName}" encontrado ✓`);
  } else {
    tgSpinner.stop('Telegram: Token inválido ✗');
    p.log.warning('Token não reconhecido pelo Telegram. Verifique com @BotFather.');
    const continueAnyway = await p.confirm({ message: 'Continuar mesmo assim?' });
    if (p.isCancel(continueAnyway) || !continueAnyway) {
      p.cancel('Setup cancelado.');
      process.exit(0);
    }
  }

  // ─── Step 5: Owner Info ──────────────────────────────────

  const ownerName = await p.text({
    message: 'Seu nome (Thor vai te chamar assim):',
    placeholder: 'Lucas',
    initialValue: 'Lucas',
  });

  if (!p.isCancel(ownerName)) {
    config.OWNER_NAME = ownerName as string;
  }

  const ownerId = await p.text({
    message: 'Seu Telegram ID numérico:',
    placeholder: '123456789',
    validate(value) {
      if (!value || !/^\d+$/.test(value)) return 'Deve ser um número (use @userinfobot pra descobrir)';
      return undefined;
    },
  });

  if (p.isCancel(ownerId)) {
    p.cancel('Setup cancelado.');
    process.exit(0);
  }

  config.OWNER_TELEGRAM_ID = ownerId as string;

  // ─── Step 6: PostgreSQL ──────────────────────────────────

  const pgMode = await p.select({
    message: 'PostgreSQL:',
    options: [
      { value: 'url', label: 'Já tenho — vou informar a URL de conexão' },
      { value: 'local', label: 'Instalar localmente (Linux)', hint: 'Instala via apt e configura automaticamente' },
      { value: 'docker', label: 'Usar Docker', hint: 'docker run postgres' },
      { value: 'skip', label: 'Pular por enquanto', hint: 'Configuro depois manualmente' },
    ],
  });

  if (p.isCancel(pgMode)) {
    p.cancel('Setup cancelado.');
    process.exit(0);
  }

  if (pgMode === 'url') {
    const pgUrl = await p.text({
      message: 'PostgreSQL connection string:',
      placeholder: 'postgresql://user:pass@localhost:5432/turionz',
      validate(value) {
        if (!validatePostgresUrl(value || '')) return 'Deve começar com postgresql:// ou postgres://';
        return undefined;
      },
    });

    if (!p.isCancel(pgUrl)) {
      config.DATABASE_URL = pgUrl as string;
    }
  } else if (pgMode === 'local') {
    const pgSpinner = p.spinner();
    pgSpinner.start('Instalando PostgreSQL...');

    try {
      runCmd('sudo apt update -y', false);
      runCmd('sudo apt install -y postgresql postgresql-contrib', false);
      runCmd('sudo systemctl start postgresql', false);
      runCmd('sudo systemctl enable postgresql', false);

      // Create database and user
      runCmd('sudo -u postgres psql -c "CREATE USER turionz WITH PASSWORD \'turionz123\';" 2>/dev/null || true');
      runCmd('sudo -u postgres psql -c "CREATE DATABASE turionz OWNER turionz;" 2>/dev/null || true');
      runCmd('sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE turionz TO turionz;"');

      config.DATABASE_URL = 'postgresql://turionz:turionz123@localhost:5432/turionz';
      pgSpinner.stop('PostgreSQL instalado e configurado ✓');
      p.log.info(`URL: ${config.DATABASE_URL}`);
    } catch {
      pgSpinner.stop('Erro na instalação do PostgreSQL ✗');
      p.log.warning('Instale manualmente: sudo apt install postgresql');
    }
  } else if (pgMode === 'docker') {
    const pgSpinner = p.spinner();
    pgSpinner.start('Iniciando PostgreSQL via Docker...');

    try {
      runCmd('docker run -d --name turionz-postgres -e POSTGRES_USER=turionz -e POSTGRES_PASSWORD=turionz123 -e POSTGRES_DB=turionz -p 5432:5432 --restart unless-stopped postgres:16-alpine');
      config.DATABASE_URL = 'postgresql://turionz:turionz123@localhost:5432/turionz';
      pgSpinner.stop('PostgreSQL Docker rodando ✓');
      p.log.info(`URL: ${config.DATABASE_URL}`);
    } catch {
      pgSpinner.stop('Erro ao iniciar Docker ✗');
      p.log.warning('Verifique se o Docker está instalado e rodando.');
    }
  } else {
    config.DATABASE_URL = 'postgresql://user:pass@localhost:5432/turionz';
    p.log.warning('PostgreSQL não configurado. Preencha DATABASE_URL no .env antes de rodar.');
  }

  // ─── Step 7: Advanced (Manual mode) ──────────────────────

  if (mode === 'manual') {
    const maxIter = await p.text({
      message: 'Máximo de iterações do Agent Loop:',
      initialValue: '5',
    });
    if (!p.isCancel(maxIter)) config.MAX_ITERATIONS = maxIter as string;

    const ctxWindow = await p.text({
      message: 'Tamanho da janela de contexto (tokens):',
      initialValue: '150000',
    });
    if (!p.isCancel(ctxWindow)) config.CONTEXT_WINDOW_SIZE = ctxWindow as string;

    // Optional: Discord
    const wantsDiscord = await p.confirm({ message: 'Configurar Discord?', initialValue: false });
    if (!p.isCancel(wantsDiscord) && wantsDiscord) {
      const discordToken = await p.text({ message: 'Discord Bot Token:', placeholder: '' });
      if (!p.isCancel(discordToken)) config.DISCORD_BOT_TOKEN = discordToken as string;

      const discordId = await p.text({ message: 'Seu Discord ID:', placeholder: '' });
      if (!p.isCancel(discordId)) config.OWNER_DISCORD_ID = discordId as string;
    }
  }

  // ─── Step 8: Write .env ──────────────────────────────────

  const writeSpinner = p.spinner();
  writeSpinner.start('Salvando configuração...');

  writeEnvFile(config);

  writeSpinner.stop('.env criado ✓');

  // ─── Step 9: Install Dependencies ────────────────────────

  const installSpinner = p.spinner();
  installSpinner.start('Instalando dependências (npm install)...');

  try {
    runCmd('npm install', false);
    installSpinner.stop('Dependências instaladas ✓');
  } catch {
    installSpinner.stop('Erro ao instalar dependências ✗');
    p.log.warning('Execute manualmente: npm install');
  }

  // ─── Step 10: Build ──────────────────────────────────────

  const buildSpinner = p.spinner();
  buildSpinner.start('Compilando TypeScript (npm run build)...');

  try {
    runCmd('npm run build', false);
    buildSpinner.stop('Build completo ✓');
  } catch {
    buildSpinner.stop('Erro no build ✗');
    p.log.warning('Execute manualmente: npm run build');
  }

  // ─── Step 11: Ensure Personality Files ───────────────────

  const soulFiles = ['SOUL.md', 'IDENTITY.md', 'MEMORY.md'];
  const missingSoul = soulFiles.filter(f => !fs.existsSync(path.join(SOUL_DIR, f)));

  if (missingSoul.length > 0) {
    p.log.warning(`Arquivos de personalidade faltando: ${missingSoul.join(', ')}`);
    p.log.info('Thor vai usar personalidade padrão até você configurar.');
  } else {
    p.log.success('Personalidade (SOUL.md, IDENTITY.md, MEMORY.md) ✓');
  }

  // ─── Step 12: Auto-Start ─────────────────────────────────

  const autoStart = await p.select({
    message: 'Configurar auto-start (Thor liga com o sistema)?',
    options: [
      { value: 'systemd', label: 'systemd (Linux)', hint: 'Recomendado para servidores' },
      { value: 'pm2', label: 'PM2 (Node.js)', hint: 'Process manager multiplataforma' },
      { value: 'skip', label: 'Pular', hint: 'Configuro depois' },
    ],
  });

  if (!p.isCancel(autoStart)) {
    if (autoStart === 'systemd') {
      const asSpinner = p.spinner();
      asSpinner.start('Configurando systemd...');

      try {
        runCmd(`bash ${path.join(process.cwd(), 'scripts/autostart-linux.sh')} install`, false);
        asSpinner.stop('systemd service instalado ✓');
        p.log.info('Comandos: sudo systemctl start turionz | status turionz | stop turionz');
      } catch {
        asSpinner.stop('Erro ao configurar systemd ✗');
        p.log.info('Execute manualmente: bash scripts/autostart-linux.sh install');
      }
    } else if (autoStart === 'pm2') {
      const pm2Spinner = p.spinner();
      pm2Spinner.start('Configurando PM2...');

      try {
        runCmd('npm install -g pm2 2>/dev/null || true');
        runCmd(`pm2 start ${path.join(process.cwd(), 'dist/index.js')} --name turionz`);
        runCmd('pm2 save');
        runCmd('pm2 startup 2>/dev/null || true');
        pm2Spinner.stop('PM2 configurado ✓');
        p.log.info('Comandos: pm2 status | pm2 logs turionz | pm2 restart turionz');
      } catch {
        pm2Spinner.stop('Erro ao configurar PM2 ✗');
        p.log.info('Instale PM2: npm install -g pm2');
      }
    }
  }

  // ─── Step 13: Summary ────────────────────────────────────

  p.note(
    [
      `Modelo principal:  ${config.MAIN_MODEL}`,
      `Modelo sub-agents: ${config.SUB_AGENT_DEFAULT_MODEL}`,
      `Telegram bot:      ${tgResult.valid ? tgResult.botName : 'Não validado'}`,
      `Owner:             ${config.OWNER_NAME} (${config.OWNER_TELEGRAM_ID})`,
      `PostgreSQL:        ${config.DATABASE_URL ? '✓ Configurado' : '✗ Pendente'}`,
      `Auto-start:        ${p.isCancel(autoStart) || autoStart === 'skip' ? 'Não configurado' : autoStart}`,
      '',
      'Para iniciar manualmente:',
      '  npm start',
      '',
      'Para ver logs:',
      '  pm2 logs turionz   (se PM2)',
      '  journalctl -u turionz -f   (se systemd)',
    ].join('\n'),
    'Resumo da Configuração'
  );

  p.outro('TurionZ (Thor) está pronto! ⚡ Bolla Network');
}

main().catch((error) => {
  console.error('Setup error:', error);
  process.exit(1);
});
